### ISSUE TITLE
Question: is the project Godot related?

### ISSUE THREAD

**Issue by me2beats** [eukara/freehl#4]
Hi cool project!
Is the project somehow related to Godot Engine?
Sorry for asking it in issues (I don't use Matrix)
PS: asking it because I saw this link in a (inofficial) Godot digest

**Comment by MissLav** [comment]
nope
it uses fteqw as the engine base 
btw curious could u post the link to the godot digest

**Comment by me2beats** [comment]
Thanks for clarifying it, I think I can close the issue then:)
this is the link:
https://thisweekingodot.com/posts/issue-68
