### ISSUE TITLE
missing crosshairs

### ISSUE THREAD

**Issue by atomGit** [eukara/freehl#6]
i'm using the 02-07-2023 binaries and i noticed when i got to the weapons part of the training course, i had no crosshairs and the option in the advanced controls is always disabled when i restart the game

if i set crosshair "1" in the cfg, the setting is saved, but i still have no crosshairs

i'm noticing other settings are not always saved either

**Comment by eukara** [comment]
On some resolutions, because these are crosshair graphics with pixel-thin lines, they may disappear.
I already round their coordinates so should not get hidden in-between pixels. However there may be other precision issues at play. What resolution is the game running at?

**Comment by atomGit** [comment]
i tried different resolutions - 640x480 and 1920x1080, however it sure didn't seem like the 640x480 res was actually being used so i'm not sure 

if you can tell me how to load the game and bypass the train sequence, i'll be glad to test but i do not remember all the cvars - i remember `sv_cheats 1` but i forget how to load a level or give items

**Comment by eukara** [comment]
`map c1a0` is something you can do, but as described in the readme of the project, Singleplayer is not yet supported. Your mileage may vary.

**Comment by eukara** [comment]
I have implemented a hack that'll shift the crosshair coordinates by a smidge. It may not work for every non-standard resolution - so I'll leave this open. Still it's a problem that ultimately goes through the engine and the way it handles upscaling 2D resources via the 'vid_conautoscale' cvar. It should round to the nearest int for elements like these.
